package mimetype

import (
	"encoding/json"
	"testing"
)

func Test_MimeType_Coverage(t *testing.T) {
	all := []Variant{Application, Audio, Font, Image, Message, Model, Multipart, Text, Video, Invalid}
	for _, v := range all {
		_ = v.ValueByte()
		_ = v.ValueInt()
		_ = v.ValueInt8()
		_ = v.ValueInt16()
		_ = v.ValueInt32()
		_ = v.ValueUInt16()
		_ = v.Value()
		_ = v.ValueString()
		_ = v.Name()
		_ = v.NameValue()
		_ = v.String()
		_ = v.ToNumberString()
		_ = v.RangeNamesCsv()
		_ = v.TypeName()
		_ = v.AllNameValues()
		_ = v.RangesByte()
		_ = v.RangesDynamicMap()
		_ = v.IntegerEnumRanges()
		_ = v.MinByte()
		_ = v.MaxByte()
		_ = v.MinInt()
		_ = v.MaxInt()
		_ = v.MinValueString()
		_ = v.MaxValueString()
		_, _ = v.MinMaxAny()
		_ = v.Format("name")
		_ = v.EnumType()
		_ = v.IsApplication()
		_ = v.IsAudio()
		_ = v.IsFont()
		_ = v.IsImage()
		_ = v.IsMessage()
		_ = v.IsModel()
		_ = v.IsMultipart()
		_ = v.IsText()
		_ = v.IsVideo()
		_ = v.IsMedia()
		_ = v.IsTextual()
		_ = v.IsBinary()
		_ = v.IsEqual(v)
		_ = v.IsValueEqual(v.ValueByte())
		_ = v.IsByteValueEqual(v.ValueByte())
		_ = v.IsNameEqual(v.Name())
		_ = v.IsAboveOrEqual(v)
		_ = v.IsLowerOrEqual(v)
		_ = v.IsAnyOf(v)
		_ = v.IsAnyValuesEqual(v.ValueByte())
		_ = v.IsAnyNamesOf(v.Name())
		_ = v.IsValid()
		_ = v.IsInvalid()
		_ = v.OnlySupportedErr("Text")
		_ = v.OnlySupportedMsgErr("m", "Text")
		_ = v.ToPtr()
		_ = v.Json()
		_ = v.JsonPtr()
		_ = v.AsJsoner()
		_ = v.AsJsonContractsBinder()
		_ = v.AsJsonMarshaller()
		_ = v.AsBasicByteEnumContractsBinder()
		_ = v.AsBasicEnumContractsBinder()

		raw, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		var rt Variant
		_ = json.Unmarshal(raw, &rt)
	}

	_ = FromContentType("text/html; charset=utf-8")
	_ = FromContentType("application/json")
	_ = FromContentType("audio/mpeg")
	_ = FromContentType("video/mp4")
	_ = FromContentType("image/png")
	_ = FromContentType("font/woff2")
	_ = FromContentType("message/rfc822")
	_ = FromContentType("model/gltf+json")
	_ = FromContentType("multipart/form-data")
	_ = FromContentType("garbage")
	_ = FromContentType("")
}
