package webservercmdnames

import (
	"github.com/alimtvnetwork/core-v8/coredata/coredynamic"
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	Ranges = [...]string{
		Invalid:                "Invalid",
		Help:                   "Help",
		AddDomain:              "AddDomain",
		AddDomainWithSsl:       "AddDomainWithSsl",
		RemoveDomain:           "RemoveDomain",
		RemoveDomainSsl:        "RemoveDomainSsl",
		ChangeDomainPort:       "ChangeDomainPort",
		ChangeDomainOwner:      "ChangeDomainOwner",
		BanDomain:              "BanDomain",
		ConfigurePresents:      "ConfigurePresents",
		DomainAlias:            "DomainAlias",
		DomainPark:             "DomainPark",
		BackupStateConfig:      "BackupStateConfig",
		BackupAllConfig:        "BackupAllConfig",
		BackupState:            "BackupState",
		RevertBackupState:      "RevertBackupState",
		RevertBackupStateAll:   "RevertBackupStateAll",
		StateDiff:              "StateDiff",
		StateHistories:         "StateHistories",
		ShowDirtyStates:        "ShowDirtyStates",
		LastStates:             "LastStates",
		Sync:                   "Sync",
		SyncNow:                "SyncNow",
		SyncForce:              "SyncForce",
		CurrentStateName:       "CurrentStateName",
		Histories:              "Histories",
		Macro:                  "Macro",
		AddLocation:            "AddLocation",
		AddSsl:                 "AddSsl",
		DryRunSsl:              "DryRunSsl",
		RenewSsl:               "RenewSsl",
		RemoveSsl:              "RemoveSsl",
		MoveSsl:                "MoveSsl",
		BackupSsl:              "BackupSsl",
		RevokeSsl:              "RevokeSsl",
		AutoSsl:                "AutoSsl",
		AutoRenewSsl:           "AutoRenewSsl",
		RemoveSslAll:           "RemoveSslAll",
		RemoveAll:              "RemoveAll",
		SslChallenge:           "SslChallenge",
		HttpSslChallenge:       "HttpSslChallenge",
		DnsSslChallenge:        "DnsSslChallenge",
		ExportConfigSpecific:   "ExportConfigSpecific",
		ExportConfigAll:        "ExportConfigAll",
		ImportConfigSpecific:   "ImportConfigSpecific",
		ImportConfigAll:        "ImportConfigAll",
		SearchDomains:          "SearchDomains",
		SearchServers:          "SearchServers",
		RootDir:                "RootDir",
		RootDirChange:          "RootDirChange",
		RemoveRootDir:          "RemoveRootDir",
		ApplyChmod:             "ApplyChmod",
		ApplyChown:             "ApplyChown",
		ApplyDefaultChmod:      "ApplyDefaultChmod",
		ApplyDefaultPermission: "ApplyDefaultPermission",
		WhichPort:              "WhichPort",
		WhichPorts:             "WhichPorts",
		WhichPortHttp:          "WhichPortHttp",
		WhichPortSsl:           "WhichPortSsl",
		ListLocation:           "ListLocation",
		ListServers:            "ListServers",
		ListDomains:            "ListDomains",
		ListPorts:              "ListPorts",
		ListSslEnabledServers:  "ListSslEnabledServers",
		Backup:                 "Backup",
		Import:                 "Import",
	}

	BasicEnumImpl = enumimpl.New.BasicByte.UsingTypeSlice(
		coredynamic.TypeName(Invalid),
		Ranges[:])
)
