package firewallcmdnames

import (
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	Ranges = [...]string{
		Invalid:                 "Invalid",
		Help:                    "Help",
		Log:                     "Log",
		LogJson:                 "LogJson",
		Status:                  "Status",
		VerboseStatus:           "VerboseStatus",
		IsRunning:               "IsRunning",
		Install:                 "Install",
		Initialize:              "Initialize",
		AddRule:                 "AddRule",
		RemoveRule:              "RemoveRule",
		PortProtocol:            "PortProtocol",
		Enable:                  "Enable",
		Disable:                 "Disable",
		EnablePort:              "EnablePort",
		DisablePort:             "DisablePort",
		EnableProtocol:          "EnableProtocol",
		DisableProtocol:         "DisableProtocol",
		EnablePortProtocol:      "EnablePortProtocol",
		DisablePortProtocol:     "DisablePortProtocol",
		ListVerbose:             "ListVerbose",
		PortList:                "PortList",
		ProtocolsList:           "ProtocolsList",
		NothingEnabled:          "NothingEnabled",
		AllEnabled:              "AllEnabled",
		SshEnable:               "SshEnable",
		SshDisable:              "SshDisable",
		RejectPorts:             "RejectPorts",
		DenyPorts:               "DenyPorts",
		RejectPortsWithProtocol: "RejectPortsWithProtocol",
		DenyPortsWithProtocol:   "DenyPortsWithProtocol",
		AllowPorts:              "AllowPorts",
		AcceptPorts:             "AcceptPorts",
		AllowPortsWithProtocol:  "AllowPortsWithProtocol",
		AcceptPortsWithProtocol: "AcceptPortsWithProtocol",
		WhitelistIps:            "WhitelistIps",
		BlacklistIps:            "BlacklistIps",
		ListBackListedIps:       "ListBackListedIps",
		ListWhiteListedIps:      "ListWhiteListedIps",
		IsPortsEnabled:          "IsPortsEnabled",
		IsPortsDisabled:         "IsPortsDisabled",
		IsIpsWhitelisted:        "IsIpsWhitelisted",
		IsIpsBlacklisted:        "IsIpsBlacklisted",
		OpenedPortsList:         "OpenedPortsList",
		EnabledPortsList:        "EnabledPortsList",
		DisablePortsList:        "DisablePortsList",
		EnabledPortsListJson:    "EnabledPortsListJson",
		DisablePortsListJson:    "DisablePortsListJson",
		ListJson:                "ListJson",
		List:                    "List",
		Search:                  "Search",
		Histories:               "Histories",
		StateChange:             "StateChange",
		MacroHistories:          "MacroHistories",
		RemoveMacro:             "RemoveMacro",
		ExportMacro:             "ExportMacro",
		ImportMacro:             "ImportMacro",
		Backup:                  "Backup",
		Import:                  "Import",
	}

	aliasMap = map[string]byte{
		"init":                  Initialize.Value(),
		"is-running":            IsRunning.Value(),
		"verbose":               VerboseStatus.Value(),
		"verbose-status":        VerboseStatus.Value(),
		"status-verbose":        VerboseStatus.Value(),
		"add-rule":              AddRule.Value(),
		"remove-rule":           RemoveRule.Value(),
		"allow-port":            AllowPorts.Value(),
		"deny-port":             DenyPorts.Value(),
		"list":                  List.Value(),
		"protocol-port":         PortProtocol.Value(),
		"port-protocol":         PortProtocol.Value(),
		"enable-protocol":       EnableProtocol.Value(),
		"disable-protocol":      DisableProtocol.Value(),
		"enable-port-protocol":  EnablePortProtocol.Value(),
		"disable-port-protocol": DisablePortProtocol.Value(),
		"ports-list":            PortList.Value(),
		"protocols-list":        ProtocolsList.Value(),
		"none-enable":           ProtocolsList.Value(),
		"all-enable":            AllEnabled.Value(),
		"reject-ports":          RejectPorts.Value(),
		"deny-ports":            DenyPorts.Value(),
		"enable-ssh":            SshEnable.Value(),
		"disable-ssh":           SshDisable.Value(),
		"is-port-enabled":       IsPortsEnabled.Value(),
		"is-port-disabled":      IsPortsDisabled.Value(),
		"is-ips-allowed":        IsIpsWhitelisted.Value(),
		"is-ips-denied":         IsIpsBlacklisted.Value(),
		"open-ports":            OpenedPortsList.Value(),
		"disabled-ports":        DisablePortsList.Value(),
		"whitelist-ips":         WhitelistIps.Value(),
		"blacklist-ips":         BlacklistIps.Value(),
		"search":                Search.Value(),
		"deny-all":              NothingEnabled.Value(),
	}

	BasicEnumImpl = enumimpl.New.BasicByte.DefaultWithAliasMapAllCases(
		Invalid,
		Ranges[:],
		aliasMap)
)
