package creationtests

import "github.com/alimtvnetwork/enum-v1/pathpatterntype"

var pathPatternTypeCreationTestCases = [...]PathPatternTypeCreationTestWrapper{
	pathpatterntype.Invalid: {
		PathType:                 pathpatterntype.Invalid,
		Name:                     "Invalid",
		FullName:                 "",
		CurlyFullName:            "",
		CompiledTemplateFullPath: ``,
		AssociatedTemplatePaths: []string{
			"",
		},
	},
	pathpatterntype.Root: {
		PathType:                 pathpatterntype.Root,
		Name:                     "Root",
		FullName:                 "root",
		CurlyFullName:            "{root}",
		CompiledTemplateFullPath: `{root}`,
		AssociatedTemplatePaths: []string{
			"{root}",
		},
	},
	pathpatterntype.VariableDir: {
		PathType:                 pathpatterntype.VariableDir,
		Name:                     "VariableDir",
		FullName:                 "var",
		CurlyFullName:            "{var}",
		CompiledTemplateFullPath: `{var}`,
		AssociatedTemplatePaths: []string{
			"{var}",
		},
	},
	pathpatterntype.App: {
		PathType:                 pathpatterntype.App,
		Name:                     "App",
		FullName:                 "app",
		CurlyFullName:            "{app}",
		CompiledTemplateFullPath: `{app}`,
		AssociatedTemplatePaths: []string{
			"{app}",
		},
	},
	pathpatterntype.AppCore: {
		PathType:                 pathpatterntype.AppCore,
		Name:                     "AppCore",
		FullName:                 "app-core",
		CurlyFullName:            "{app-core}",
		CompiledTemplateFullPath: `{app-core}`,
		AssociatedTemplatePaths: []string{
			"{app-core}",
		},
	},
	pathpatterntype.Id: {
		PathType:                 pathpatterntype.Id,
		Name:                     "Id",
		FullName:                 "id",
		CurlyFullName:            "{id}",
		CompiledTemplateFullPath: `{id}`,
		AssociatedTemplatePaths: []string{
			"{id}",
		},
	},
	pathpatterntype.File: {
		PathType:                 pathpatterntype.File,
		Name:                     "File",
		FullName:                 "file",
		CurlyFullName:            "{file}",
		CompiledTemplateFullPath: `{file}`,
		AssociatedTemplatePaths: []string{
			"{file}",
		},
	},
	pathpatterntype.VarApp: {
		PathType:                 pathpatterntype.VarApp,
		Name:                     "VarApp",
		FullName:                 "var-app",
		CurlyFullName:            "{var-app}",
		CompiledTemplateFullPath: `{var}\{app}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
		},
	},
	pathpatterntype.AppConfigStore: {
		PathType:                 pathpatterntype.AppConfigStore,
		Name:                     "AppConfigStore",
		FullName:                 "app-config-store",
		CurlyFullName:            "{app-config-store}",
		CompiledTemplateFullPath: `{app}\{config-store}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{config-store}",
		},
	},
	pathpatterntype.AppLog: {
		PathType:                 pathpatterntype.AppLog,
		Name:                     "AppLog",
		FullName:                 "app-log",
		CurlyFullName:            "{app-log}",
		CompiledTemplateFullPath: `{app}\{log}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{log}",
		},
	},
	pathpatterntype.AppDb: {
		PathType:                 pathpatterntype.AppDb,
		Name:                     "AppDb",
		FullName:                 "app-db",
		CurlyFullName:            "{app-db}",
		CompiledTemplateFullPath: `{app}\{database}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
		},
	},
	pathpatterntype.AppTest: {
		PathType:                 pathpatterntype.AppTest,
		Name:                     "AppTest",
		FullName:                 "app-test",
		CurlyFullName:            "{app-test}",
		CompiledTemplateFullPath: `{app}\{test}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{test}",
		},
	},
	pathpatterntype.AppTemp: {
		PathType:                 pathpatterntype.AppTemp,
		Name:                     "AppTemp",
		FullName:                 "app-temp",
		CurlyFullName:            "{app-temp}",
		CompiledTemplateFullPath: `{app}\{temp}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{temp}",
		},
	},
	pathpatterntype.VarAppTemp: {
		PathType:                 pathpatterntype.VarAppTemp,
		Name:                     "VarAppTemp",
		FullName:                 "var-app-temp",
		CurlyFullName:            "{var-app-temp}",
		CompiledTemplateFullPath: `{var}\{app}\{temp}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{temp}",
		},
	},
	pathpatterntype.Relative: {
		PathType:                 pathpatterntype.Relative,
		Name:                     "Relative",
		FullName:                 "relative",
		CurlyFullName:            "{relative}",
		CompiledTemplateFullPath: `{relative}`,
		AssociatedTemplatePaths: []string{
			"{relative}",
		},
	},
	pathpatterntype.RelativeId: {
		PathType:                 pathpatterntype.RelativeId,
		Name:                     "RelativeId",
		FullName:                 "relative-id",
		CurlyFullName:            "{relative-id}",
		CompiledTemplateFullPath: `{relative}\{id}`,
		AssociatedTemplatePaths: []string{
			"{relative}",
			"{id}",
		},
	},
	pathpatterntype.RelativeIdFile: {
		PathType:                 pathpatterntype.RelativeIdFile,
		Name:                     "RelativeIdFile",
		FullName:                 "relative-id-file",
		CurlyFullName:            "{relative-id-file}",
		CompiledTemplateFullPath: `{relative}\{id}\{file}`,
		AssociatedTemplatePaths: []string{
			"{relative}",
			"{id}",
			"{file}",
		},
	},
	pathpatterntype.AppRelative: {
		PathType:                 pathpatterntype.AppRelative,
		Name:                     "AppRelative",
		FullName:                 "app-relative",
		CurlyFullName:            "{app-relative}",
		CompiledTemplateFullPath: `{app}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{relative}",
		},
	},
	pathpatterntype.AppRelativeId: {
		PathType:                 pathpatterntype.AppRelativeId,
		Name:                     "AppRelativeId",
		FullName:                 "app-relative-id",
		CurlyFullName:            "{app-relative-id}",
		CompiledTemplateFullPath: `{app}\{relative}\{id}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{relative}",
			"{id}",
		},
	},
	pathpatterntype.AppRelativeIdFile: {
		PathType:                 pathpatterntype.AppRelativeIdFile,
		Name:                     "AppRelativeIdFile",
		FullName:                 "app-relative-id-file",
		CurlyFullName:            "{app-relative-id-file}",
		CompiledTemplateFullPath: `{app}\{relative}\{id}\{file}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{relative}",
			"{id}",
			"{file}",
		},
	},
	pathpatterntype.PrefixApp: {
		PathType:                 pathpatterntype.PrefixApp,
		Name:                     "PrefixApp",
		FullName:                 "prefix-app",
		CurlyFullName:            "{prefix-app}",
		CompiledTemplateFullPath: `{prefix}\{app}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
		},
	},
	pathpatterntype.PrefixAppRelative: {
		PathType:                 pathpatterntype.PrefixAppRelative,
		Name:                     "PrefixAppRelative",
		FullName:                 "prefix-app-relative",
		CurlyFullName:            "{prefix-app-relative}",
		CompiledTemplateFullPath: `{prefix}\{app}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
			"{relative}",
		},
	},
	pathpatterntype.PrefixAppRelativeId: {
		PathType:                 pathpatterntype.PrefixAppRelativeId,
		Name:                     "PrefixAppRelativeId",
		FullName:                 "prefix-app-relative-id",
		CurlyFullName:            "{prefix-app-relative-id}",
		CompiledTemplateFullPath: `{prefix}\{app}\{relative}\{id}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
			"{relative}",
			"{id}",
		},
	},
	pathpatterntype.PrefixAppRelativeIdFile: {
		PathType:                 pathpatterntype.PrefixAppRelativeIdFile,
		Name:                     "PrefixAppRelativeIdFile",
		FullName:                 "prefix-app-relative-id- file",
		CurlyFullName:            "{prefix-app-relative-id- file}",
		CompiledTemplateFullPath: `{prefix}\{app}\{relative}\{id}\{file}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
			"{relative}",
			"{id}",
			"{file}",
		},
	},
	pathpatterntype.TempRoot: {
		PathType:                 pathpatterntype.TempRoot,
		Name:                     "TempRoot",
		FullName:                 "temp-root",
		CurlyFullName:            "{temp-root}",
		CompiledTemplateFullPath: `{temp-root}`,
		AssociatedTemplatePaths: []string{
			"{temp-root}",
		},
	},
	pathpatterntype.AppInstalled: {
		PathType:                 pathpatterntype.AppInstalled,
		Name:                     "AppInstalled",
		FullName:                 "app-installed",
		CurlyFullName:            "{app-installed}",
		CompiledTemplateFullPath: `{app-installed}`,
		AssociatedTemplatePaths: []string{
			"{app-installed}",
		},
	},
	pathpatterntype.AppDownloads: {
		PathType:                 pathpatterntype.AppDownloads,
		Name:                     "AppDownloads",
		FullName:                 "app-downloads",
		CurlyFullName:            "{app-downloads}",
		CompiledTemplateFullPath: `{app}\{downloads}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{downloads}",
		},
	},
	pathpatterntype.Home: {
		PathType:                 pathpatterntype.Home,
		Name:                     "Home",
		FullName:                 "home",
		CurlyFullName:            "{home}",
		CompiledTemplateFullPath: `{home}`,
		AssociatedTemplatePaths: []string{
			"{home}",
		},
	},
	pathpatterntype.User: {
		PathType:                 pathpatterntype.User,
		Name:                     "User",
		FullName:                 "user",
		CurlyFullName:            "{user}",
		CompiledTemplateFullPath: `{user}`,
		AssociatedTemplatePaths: []string{
			"{user}",
		},
	},
	pathpatterntype.HomeUser: {
		PathType:                 pathpatterntype.HomeUser,
		Name:                     "HomeUser",
		FullName:                 "home-user",
		CurlyFullName:            "{home-user}",
		CompiledTemplateFullPath: `{home}\{user}`,
		AssociatedTemplatePaths: []string{
			"{home}",
			"{user}",
		},
	},
	pathpatterntype.HomeUserApp: {
		PathType:                 pathpatterntype.HomeUserApp,
		Name:                     "HomeUserApp",
		FullName:                 "home-user-app",
		CurlyFullName:            "{home-user-app}",
		CompiledTemplateFullPath: `{home}\{user}\{app}`,
		AssociatedTemplatePaths: []string{
			"{home}",
			"{user}",
			"{app}",
		},
	},
	pathpatterntype.UsersRoot: {
		PathType:                 pathpatterntype.UsersRoot,
		Name:                     "UsersRoot",
		FullName:                 "users-root",
		CurlyFullName:            "{users-root}",
		CompiledTemplateFullPath: `{users-root}`,
		AssociatedTemplatePaths: []string{
			"{users-root}",
		},
	},
	pathpatterntype.WebServerRoot: {
		PathType:                 pathpatterntype.WebServerRoot,
		Name:                     "WebServerRoot",
		FullName:                 "webserver-root",
		CurlyFullName:            "{webserver-root}",
		CompiledTemplateFullPath: `{webserver-root}`,
		AssociatedTemplatePaths: []string{
			"{webserver-root}",
		},
	},
	pathpatterntype.WebServerConfigsRoot: {
		PathType:                 pathpatterntype.WebServerConfigsRoot,
		Name:                     "WebServerConfigsRoot",
		FullName:                 "webserver-config-root",
		CurlyFullName:            "{webserver-config-root}",
		CompiledTemplateFullPath: `{webserver-config-root}`,
		AssociatedTemplatePaths: []string{
			"{webserver-config-root}",
		},
	},
	pathpatterntype.WebServerConfigsUsersRoot: {
		PathType:                 pathpatterntype.WebServerConfigsUsersRoot,
		Name:                     "WebServerConfigsUsersRoot",
		FullName:                 "webserver-config-users-root",
		CurlyFullName:            "{webserver-config-users-root}",
		CompiledTemplateFullPath: `{webserver-config-users-root}`,
		AssociatedTemplatePaths: []string{
			"{webserver-config-users-root}",
		},
	},
	pathpatterntype.Packages: {
		PathType:                 pathpatterntype.Packages,
		Name:                     "Packages",
		FullName:                 "packages",
		CurlyFullName:            "{packages}",
		CompiledTemplateFullPath: `{packages}`,
		AssociatedTemplatePaths: []string{
			"{packages}",
		},
	},
	pathpatterntype.Instructions: {
		PathType:                 pathpatterntype.Instructions,
		Name:                     "Instructions",
		FullName:                 "instructions",
		CurlyFullName:            "{instructions}",
		CompiledTemplateFullPath: `{instructions}`,
		AssociatedTemplatePaths: []string{
			"{instructions}",
		},
	},
	pathpatterntype.VarAppPackages: {
		PathType:                 pathpatterntype.VarAppPackages,
		Name:                     "VarAppPackages",
		FullName:                 "var-app-packages",
		CurlyFullName:            "{var-app-packages}",
		CompiledTemplateFullPath: `{var}\{app}\{packages}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{packages}",
		},
	},
	pathpatterntype.VarAppDownloads: {
		PathType:                 pathpatterntype.VarAppDownloads,
		Name:                     "VarAppDownloads",
		FullName:                 "var-app-downloads",
		CurlyFullName:            "{var-app-downloads}",
		CompiledTemplateFullPath: `{var}\{app}\{downloads}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{downloads}",
		},
	},
	pathpatterntype.VarAppInstructions: {
		PathType:                 pathpatterntype.VarAppInstructions,
		Name:                     "VarAppInstructions",
		FullName:                 "var-app-instructions",
		CurlyFullName:            "{var-app-instructions}",
		CompiledTemplateFullPath: `{var}\{app}\{instructions}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{instructions}",
		},
	},
	pathpatterntype.VarAppLog: {
		PathType:                 pathpatterntype.VarAppLog,
		Name:                     "VarAppLog",
		FullName:                 "var-app-log",
		CurlyFullName:            "{var-app-log}",
		CompiledTemplateFullPath: `{var}\{app}\{log}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{log}",
		},
	},
	pathpatterntype.VarAppLogId: {
		PathType:                 pathpatterntype.VarAppLogId,
		Name:                     "VarAppLogId",
		FullName:                 "var-app-log-id",
		CurlyFullName:            "{var-app-log-id}",
		CompiledTemplateFullPath: `{var}\{app}\{log}\{id}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{log}",
			"{id}",
		},
	},
	pathpatterntype.IdFile: {
		PathType:                 pathpatterntype.IdFile,
		Name:                     "IdFile",
		FullName:                 "id-file",
		CurlyFullName:            "{id-file}",
		CompiledTemplateFullPath: `{id}\{file}`,
		AssociatedTemplatePaths: []string{
			"{id}",
			"{file}",
		},
	},
	pathpatterntype.LogFile: {
		PathType:                 pathpatterntype.LogFile,
		Name:                     "LogFile",
		FullName:                 "log-file",
		CurlyFullName:            "{log-file}",
		CompiledTemplateFullPath: `{log}\{file}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{file}",
		},
	},
	pathpatterntype.LogId: {
		PathType:                 pathpatterntype.LogId,
		Name:                     "LogId",
		FullName:                 "log-id",
		CurlyFullName:            "{log-id}",
		CompiledTemplateFullPath: `{log}\{id}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{id}",
		},
	},
	pathpatterntype.DbId: {
		PathType:                 pathpatterntype.DbId,
		Name:                     "DbId",
		FullName:                 "db-id",
		CurlyFullName:            "{db-id}",
		CompiledTemplateFullPath: `{database}\{id}`,
		AssociatedTemplatePaths: []string{
			"{database}",
			"{id}",
		},
	},
	pathpatterntype.DbIdFile: {
		PathType:                 pathpatterntype.DbIdFile,
		Name:                     "DbIdFile",
		FullName:                 "db-id-file",
		CurlyFullName:            "{db-id-file}",
		CompiledTemplateFullPath: `{database}\{id}\{file}`,
		AssociatedTemplatePaths: []string{
			"{database}",
			"{id}",
			"{file}",
		},
	},
	pathpatterntype.ConfigStore: {
		PathType:                 pathpatterntype.ConfigStore,
		Name:                     "ConfigStore",
		FullName:                 "config-store",
		CurlyFullName:            "{config-store}",
		CompiledTemplateFullPath: `{config-store}`,
		AssociatedTemplatePaths: []string{
			"{config-store}",
		},
	},
	pathpatterntype.Log: {
		PathType:                 pathpatterntype.Log,
		Name:                     "Log",
		FullName:                 "log",
		CurlyFullName:            "{log}",
		CompiledTemplateFullPath: `{log}`,
		AssociatedTemplatePaths: []string{
			"{log}",
		},
	},
	pathpatterntype.Database: {
		PathType:                 pathpatterntype.Database,
		Name:                     "Database",
		FullName:                 "database",
		CurlyFullName:            "{database}",
		CompiledTemplateFullPath: `{database}`,
		AssociatedTemplatePaths: []string{
			"{database}",
		},
	},
	pathpatterntype.Test: {
		PathType:                 pathpatterntype.Test,
		Name:                     "Test",
		FullName:                 "test",
		CurlyFullName:            "{test}",
		CompiledTemplateFullPath: `{test}`,
		AssociatedTemplatePaths: []string{
			"{test}",
		},
	},
	pathpatterntype.Temp: {
		PathType:                 pathpatterntype.Temp,
		Name:                     "Temp",
		FullName:                 "temp",
		CurlyFullName:            "{temp}",
		CompiledTemplateFullPath: `{temp}`,
		AssociatedTemplatePaths: []string{
			"{temp}",
		},
	},
	pathpatterntype.Prefix: {
		PathType:                 pathpatterntype.Prefix,
		Name:                     "Prefix",
		FullName:                 "prefix",
		CurlyFullName:            "{prefix}",
		CompiledTemplateFullPath: `{prefix}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
		},
	},
	pathpatterntype.Downloads: {
		PathType:                 pathpatterntype.Downloads,
		Name:                     "Downloads",
		FullName:                 "downloads",
		CurlyFullName:            "{downloads}",
		CompiledTemplateFullPath: `{downloads}`,
		AssociatedTemplatePaths: []string{
			"{downloads}",
		},
	},
	pathpatterntype.Extension: {
		PathType:                 pathpatterntype.Extension,
		Name:                     "Extension",
		FullName:                 "extension",
		CurlyFullName:            "{extension}",
		CompiledTemplateFullPath: `{extension}`,
		AssociatedTemplatePaths: []string{
			"{extension}",
		},
	},
	pathpatterntype.FileWithExtension: {
		PathType:                 pathpatterntype.FileWithExtension,
		Name:                     "FileWithExtension",
		FullName:                 "file-with-extension",
		CurlyFullName:            "{file-with-extension}",
		CompiledTemplateFullPath: `{file}\{extension}`,
		AssociatedTemplatePaths: []string{
			"{file}",
			"{extension}",
		},
	},
	pathpatterntype.Webserver: {
		PathType:                 pathpatterntype.Webserver,
		Name:                     "Webserver",
		FullName:                 "web-server",
		CurlyFullName:            "{web-server}",
		CompiledTemplateFullPath: `{web-server}`,
		AssociatedTemplatePaths: []string{
			"{web-server}",
		},
	},
	pathpatterntype.PrefixAppFile: {
		PathType:                 pathpatterntype.PrefixAppFile,
		Name:                     "PrefixAppFile",
		FullName:                 "prefix-app-file",
		CurlyFullName:            "{prefix-app-file}",
		CompiledTemplateFullPath: `{prefix}\{app}\{file}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
			"{file}",
		},
	},
	pathpatterntype.AppFileWithExtension: {
		PathType:                 pathpatterntype.AppFileWithExtension,
		Name:                     "AppFileWithExtension",
		FullName:                 "app-file-with-extension",
		CurlyFullName:            "{app-file-with-extension}",
		CompiledTemplateFullPath: `{app}\{file}\{extension}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{file}",
			"{extension}",
		},
	},
	pathpatterntype.PrefixAppFileWithExtension: {
		PathType:                 pathpatterntype.PrefixAppFileWithExtension,
		Name:                     "PrefixAppFileWithExtension",
		FullName:                 "prefix-app-file-with-extension",
		CurlyFullName:            "{prefix-app-file-with-extension}",
		CompiledTemplateFullPath: `{prefix}\{app}\{file}\{extension}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{app}",
			"{file}",
			"{extension}",
		},
	},
	pathpatterntype.PrefixRelativeAppFileWithExtension: {
		PathType:                 pathpatterntype.PrefixRelativeAppFileWithExtension,
		Name:                     "PrefixRelativeAppFileWithExtension",
		FullName:                 "prefix-relative-app-file-with-extension",
		CurlyFullName:            "{prefix-relative-app-file-with-extension}",
		CompiledTemplateFullPath: `{prefix}\{relative}\{app}\{file}\{extension}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{relative}",
			"{app}",
			"{file}",
			"{extension}",
		},
	},
	pathpatterntype.UserTemp: {
		PathType:                 pathpatterntype.UserTemp,
		Name:                     "UserTemp",
		FullName:                 "user-temp",
		CurlyFullName:            "{user-temp}",
		CompiledTemplateFullPath: `{user}\{temp}`,
		AssociatedTemplatePaths: []string{
			"{user}",
			"{temp}",
		},
	},
	pathpatterntype.Audit: {
		PathType:                 pathpatterntype.Audit,
		Name:                     "Audit",
		FullName:                 "audit",
		CurlyFullName:            "{audit}",
		CompiledTemplateFullPath: `{audit}`,
		AssociatedTemplatePaths: []string{
			"{audit}",
		},
	},
	pathpatterntype.LogDb: {
		PathType:                 pathpatterntype.LogDb,
		Name:                     "LogDb",
		FullName:                 "log-database",
		CurlyFullName:            "{log-database}",
		CompiledTemplateFullPath: `{log}\{database}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{database}",
		},
	},
	pathpatterntype.LogDbFile: {
		PathType:                 pathpatterntype.LogDbFile,
		Name:                     "LogDbFile",
		FullName:                 "log-database-file",
		CurlyFullName:            "{log-database-file}",
		CompiledTemplateFullPath: `{log}\{database}\{file}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{database}",
			"{file}",
		},
	},
	pathpatterntype.LogAppDb: {
		PathType:                 pathpatterntype.LogAppDb,
		Name:                     "LogAppDb",
		FullName:                 "log-app-database",
		CurlyFullName:            "{log-app-database}",
		CompiledTemplateFullPath: `{log}\{app}\{database}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{app}",
			"{database}",
		},
	},
	pathpatterntype.LogAppDbFile: {
		PathType:                 pathpatterntype.LogAppDbFile,
		Name:                     "LogAppDbFile",
		FullName:                 "log-app-database-file",
		CurlyFullName:            "{log-app-database-file}",
		CompiledTemplateFullPath: `{log}\{app}\{database}\{file}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{app}",
			"{database}",
			"{file}",
		},
	},
	pathpatterntype.TempUser: {
		PathType:                 pathpatterntype.TempUser,
		Name:                     "TempUser",
		FullName:                 "temp-user",
		CurlyFullName:            "{temp-user}",
		CompiledTemplateFullPath: `{temp}\{user}`,
		AssociatedTemplatePaths: []string{
			"{temp}",
			"{user}",
		},
	},
	pathpatterntype.TempApp: {
		PathType:                 pathpatterntype.TempApp,
		Name:                     "TempApp",
		FullName:                 "temp-app",
		CurlyFullName:            "{temp-app}",
		CompiledTemplateFullPath: `{temp}\{app}`,
		AssociatedTemplatePaths: []string{
			"{temp}",
			"{app}",
		},
	},
	pathpatterntype.TempAudit: {
		PathType:                 pathpatterntype.TempAudit,
		Name:                     "TempAudit",
		FullName:                 "temp-audit",
		CurlyFullName:            "{temp-audit}",
		CompiledTemplateFullPath: `{temp}\{audit}`,
		AssociatedTemplatePaths: []string{
			"{temp}",
			"{audit}",
		},
	},
	pathpatterntype.LogApp: {
		PathType:                 pathpatterntype.LogApp,
		Name:                     "LogApp",
		FullName:                 "log-app",
		CurlyFullName:            "{log-app}",
		CompiledTemplateFullPath: `{log}\{app}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{app}",
		},
	},
	pathpatterntype.LogAppFile: {
		PathType:                 pathpatterntype.LogAppFile,
		Name:                     "LogAppFile",
		FullName:                 "log-app-file",
		CurlyFullName:            "{log-app-file}",
		CompiledTemplateFullPath: `{log}\{app}\{file}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{app}",
			"{file}",
		},
	},
	pathpatterntype.Random: {
		PathType:                 pathpatterntype.Random,
		Name:                     "Random",
		FullName:                 "random",
		CurlyFullName:            "{random}",
		CompiledTemplateFullPath: `{random}`,
		AssociatedTemplatePaths: []string{
			"{random}",
		},
	},
	pathpatterntype.RandomUuid: {
		PathType:                 pathpatterntype.RandomUuid,
		Name:                     "RandomUuid",
		FullName:                 "random-uuid",
		CurlyFullName:            "{random-uuid}",
		CompiledTemplateFullPath: `{random-uuid}`,
		AssociatedTemplatePaths: []string{
			"{random-uuid}",
		},
	},
	pathpatterntype.RandomNumber: {
		PathType:                 pathpatterntype.RandomNumber,
		Name:                     "RandomNumber",
		FullName:                 "random-number",
		CurlyFullName:            "{random-number}",
		CompiledTemplateFullPath: `{random-number}`,
		AssociatedTemplatePaths: []string{
			"{random-number}",
		},
	},
	pathpatterntype.AppDbFile: {
		PathType:                 pathpatterntype.AppDbFile,
		Name:                     "AppDbFile",
		FullName:                 "app-db-file",
		CurlyFullName:            "{app-db-file}",
		CompiledTemplateFullPath: `{app}\{database}\{file}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{file}",
		},
	},
	pathpatterntype.AppDbRelativeFile: {
		PathType:                 pathpatterntype.AppDbRelativeFile,
		Name:                     "AppDbRelativeFile",
		FullName:                 "app-db-relative-file",
		CurlyFullName:            "{app-db-relative-file}",
		CompiledTemplateFullPath: `{app}\{database}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.AppDbRandom: {
		PathType:                 pathpatterntype.AppDbRandom,
		Name:                     "AppDbRandom",
		FullName:                 "app-db-random",
		CurlyFullName:            "{app-db-random}",
		CompiledTemplateFullPath: `{app}\{database}\{random}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{random}",
		},
	},
	pathpatterntype.AppDbRandomRelative: {
		PathType:                 pathpatterntype.AppDbRandomRelative,
		Name:                     "AppDbRandomRelative",
		FullName:                 "app-db-random-relative",
		CurlyFullName:            "{app-db-random-relative}",
		CompiledTemplateFullPath: `{app}\{database}\{random}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{random}",
			"{relative}",
		},
	},
	pathpatterntype.AppDbRandomRelativeFile: {
		PathType:                 pathpatterntype.AppDbRandomRelativeFile,
		Name:                     "AppDbRandomRelativeFile",
		FullName:                 "app-db-random-relative-file",
		CurlyFullName:            "{app-db-random-relative-file}",
		CompiledTemplateFullPath: `{app}\{database}\{random}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{random}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.LogRandom: {
		PathType:                 pathpatterntype.LogRandom,
		Name:                     "LogRandom",
		FullName:                 "log-random",
		CurlyFullName:            "{log-random}",
		CompiledTemplateFullPath: `{log}\{random}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{random}",
		},
	},
	pathpatterntype.AppDbRandomFile: {
		PathType:                 pathpatterntype.AppDbRandomFile,
		Name:                     "AppDbRandomFile",
		FullName:                 "random-file",
		CurlyFullName:            "{random-file}",
		CompiledTemplateFullPath: `{app}\{database}\{random}\{file}`,
		AssociatedTemplatePaths: []string{
			"{app}",
			"{database}",
			"{random}",
			"{file}",
		},
	},
	pathpatterntype.LogRandomFile: {
		PathType:                 pathpatterntype.LogRandomFile,
		Name:                     "LogRandomFile",
		FullName:                 "log-random-file",
		CurlyFullName:            "{log-random-file}",
		CompiledTemplateFullPath: `{log}\{random}\{file}`,
		AssociatedTemplatePaths: []string{
			"{log}",
			"{random}",
			"{file}",
		},
	},
	pathpatterntype.VarAppRandom: {
		PathType:                 pathpatterntype.VarAppRandom,
		Name:                     "VarAppRandom",
		FullName:                 "var-app-random",
		CurlyFullName:            "{var-app-random}",
		CompiledTemplateFullPath: `{var}\{app}\{random}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{random}",
		},
	},
	pathpatterntype.VarAppRandomFile: {
		PathType:                 pathpatterntype.VarAppRandomFile,
		Name:                     "VarAppRandomFile",
		FullName:                 "var-app-random-file",
		CurlyFullName:            "{var-app-random-file}",
		CompiledTemplateFullPath: `{var}\{app}\{random}\{file}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{random}",
			"{file}",
		},
	},
	pathpatterntype.VarAppRandomRelative: {
		PathType:                 pathpatterntype.VarAppRandomRelative,
		Name:                     "VarAppRandomRelative",
		FullName:                 "var-app-random-relative",
		CurlyFullName:            "{var-app-random-relative}",
		CompiledTemplateFullPath: `{var}\{app}\{random}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{random}",
			"{relative}",
		},
	},
	pathpatterntype.VarAppRandomRelativeFile: {
		PathType:                 pathpatterntype.VarAppRandomRelativeFile,
		Name:                     "VarAppRandomRelativeFile",
		FullName:                 "var-app-random-relative-file",
		CurlyFullName:            "{var-app-random-relative-file}",
		CompiledTemplateFullPath: `{var}\{app}\{random}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{random}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.Specific: {
		PathType:                 pathpatterntype.Specific,
		Name:                     "Specific",
		FullName:                 "specific",
		CurlyFullName:            "{specific}",
		CompiledTemplateFullPath: `{specific}`,
		AssociatedTemplatePaths: []string{
			"{specific}",
		},
	},
	pathpatterntype.Backup: {
		PathType:                 pathpatterntype.Backup,
		Name:                     "Backup",
		FullName:                 "backup",
		CurlyFullName:            "{backup}",
		CompiledTemplateFullPath: `{backup}`,
		AssociatedTemplatePaths: []string{
			"{backup}",
		},
	},
	pathpatterntype.HomeBackup: {
		PathType:                 pathpatterntype.HomeBackup,
		Name:                     "HomeBackup",
		FullName:                 "home-backup",
		CurlyFullName:            "{home-backup}",
		CompiledTemplateFullPath: `{home}\{backup}`,
		AssociatedTemplatePaths: []string{
			"{home}",
			"{backup}",
		},
	},
	pathpatterntype.BackupSpecific: {
		PathType:                 pathpatterntype.BackupSpecific,
		Name:                     "BackupSpecific",
		FullName:                 "backup-specific",
		CurlyFullName:            "{backup-specific}",
		CompiledTemplateFullPath: `{backup}\{specific}`,
		AssociatedTemplatePaths: []string{
			"{backup}",
			"{specific}",
		},
	},
	pathpatterntype.BackupRelative: {
		PathType:                 pathpatterntype.BackupRelative,
		Name:                     "BackupRelative",
		FullName:                 "backup-relative",
		CurlyFullName:            "{backup-relative}",
		CompiledTemplateFullPath: `{backup}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{backup}",
			"{relative}",
		},
	},
	pathpatterntype.Ssl: {
		PathType:                 pathpatterntype.Ssl,
		Name:                     "Ssl",
		FullName:                 "ssl",
		CurlyFullName:            "{ssl}",
		CompiledTemplateFullPath: `{ssl}`,
		AssociatedTemplatePaths: []string{
			"{ssl}",
		},
	},
	pathpatterntype.WebServerSsl: {
		PathType:                 pathpatterntype.WebServerSsl,
		Name:                     "WebServerSsl",
		FullName:                 "webserver-ssl",
		CurlyFullName:            "{webserver-ssl}",
		CompiledTemplateFullPath: `{web-server}\{ssl}`,
		AssociatedTemplatePaths: []string{
			"{web-server}",
			"{ssl}",
		},
	},
	pathpatterntype.WebServerConfigUsers: {
		PathType:                 pathpatterntype.WebServerConfigUsers,
		Name:                     "WebServerConfigUsers",
		FullName:                 "webserver-config-users",
		CurlyFullName:            "{webserver-config-users}",
		CompiledTemplateFullPath: `{web-server}\{config}\{users}`,
		AssociatedTemplatePaths: []string{
			"{web-server}",
			"{config}",
			"{users}",
		},
	},
	pathpatterntype.WebServerConfigUsersSpecific: {
		PathType:                 pathpatterntype.WebServerConfigUsersSpecific,
		Name:                     "WebServerConfigUsersSpecific",
		FullName:                 "webserver-config-users-specific",
		CurlyFullName:            "{webserver-config-users-specific}",
		CompiledTemplateFullPath: `{web-server}\{config}\{users}\{specific}`,
		AssociatedTemplatePaths: []string{
			"{web-server}",
			"{config}",
			"{users}",
			"{specific}",
		},
	},
	pathpatterntype.WebServerConfigSsl: {
		PathType:                 pathpatterntype.WebServerConfigSsl,
		Name:                     "WebServerConfigSsl",
		FullName:                 "webserver-config-ssl",
		CurlyFullName:            "{webserver-config-ssl}",
		CompiledTemplateFullPath: `{web-server}\{config}\{ssl}`,
		AssociatedTemplatePaths: []string{
			"{web-server}",
			"{config}",
			"{ssl}",
		},
	},
	pathpatterntype.RelativeSsl: {
		PathType:                 pathpatterntype.RelativeSsl,
		Name:                     "RelativeSsl",
		FullName:                 "relative-ssl",
		CurlyFullName:            "{relative-ssl}",
		CompiledTemplateFullPath: `{relative}\{ssl}`,
		AssociatedTemplatePaths: []string{
			"{relative}",
			"{ssl}",
		},
	},
	pathpatterntype.VarAppBackup: {
		PathType:                 pathpatterntype.VarAppBackup,
		Name:                     "VarAppBackup",
		FullName:                 "var-app-backup",
		CurlyFullName:            "{var-app-backup}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
		},
	},
	pathpatterntype.VarAppBackupFile: {
		PathType:                 pathpatterntype.VarAppBackupFile,
		Name:                     "VarAppBackupFile",
		FullName:                 "var-app-backup-file",
		CurlyFullName:            "{var-app-backup-file}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}\{file}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
			"{file}",
		},
	},
	pathpatterntype.VarAppBackupRandom: {
		PathType:                 pathpatterntype.VarAppBackupRandom,
		Name:                     "VarAppBackupRandom",
		FullName:                 "var-app-backup-random",
		CurlyFullName:            "{var-app-backup-random}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}\{random}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
			"{random}",
		},
	},
	pathpatterntype.VarAppBackupRandomFile: {
		PathType:                 pathpatterntype.VarAppBackupRandomFile,
		Name:                     "VarAppBackupRandomFile",
		FullName:                 "var-app-backup-random-file",
		CurlyFullName:            "{var-app-backup-random-file}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}\{random}\{file}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
			"{random}",
			"{file}",
		},
	},
	pathpatterntype.VarAppBackupRandomRelative: {
		PathType:                 pathpatterntype.VarAppBackupRandomRelative,
		Name:                     "VarAppBackupRandomRelative",
		FullName:                 "var-app-backup-random-relative",
		CurlyFullName:            "{var-app-backup-random-relative}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}\{random}\{relative}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
			"{random}",
			"{relative}",
		},
	},
	pathpatterntype.VarAppBackupRandomRelativeFile: {
		PathType:                 pathpatterntype.VarAppBackupRandomRelativeFile,
		Name:                     "VarAppBackupRandomRelativeFile",
		FullName:                 "var-app-backup-random-relative-file",
		CurlyFullName:            "{var-app-backup-random-relative-file}",
		CompiledTemplateFullPath: `{var}\{app}\{backup}\{random}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{var}",
			"{app}",
			"{backup}",
			"{random}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.Config: {
		PathType:                 pathpatterntype.Config,
		Name:                     "Config",
		FullName:                 "config",
		CurlyFullName:            "{config}",
		CompiledTemplateFullPath: `{config}`,
		AssociatedTemplatePaths: []string{
			"{config}",
		},
	},
	pathpatterntype.Users: {
		PathType:                 pathpatterntype.Users,
		Name:                     "Users",
		FullName:                 "users",
		CurlyFullName:            "{users}",
		CompiledTemplateFullPath: `{users}`,
		AssociatedTemplatePaths: []string{
			"{users}",
		},
	},
	pathpatterntype.BackupFile: {
		PathType:                 pathpatterntype.BackupFile,
		Name:                     "BackupFile",
		FullName:                 "backup-file",
		CurlyFullName:            "{backup-file}",
		CompiledTemplateFullPath: `{backup}\{file}`,
		AssociatedTemplatePaths: []string{
			"{backup}",
			"{file}",
		},
	},
	pathpatterntype.BackupRelativeFile: {
		PathType:                 pathpatterntype.BackupRelativeFile,
		Name:                     "BackupRelativeFile",
		FullName:                 "backup-relative-file",
		CurlyFullName:            "{backup-relative-file}",
		CompiledTemplateFullPath: `{backup}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{backup}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.PrefixBackup: {
		PathType:                 pathpatterntype.PrefixBackup,
		Name:                     "PrefixBackup",
		FullName:                 "prefix-backup",
		CurlyFullName:            "{prefix-backup}",
		CompiledTemplateFullPath: `{prefix}\{backup}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{backup}",
		},
	},
	pathpatterntype.PrefixBackupFile: {
		PathType:                 pathpatterntype.PrefixBackupFile,
		Name:                     "PrefixBackupFile",
		FullName:                 "prefix-backup-file",
		CurlyFullName:            "{prefix-backup-file}",
		CompiledTemplateFullPath: `{prefix}\{backup}\{file}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{backup}",
			"{file}",
		},
	},
	pathpatterntype.PrefixBackupRelativeFile: {
		PathType:                 pathpatterntype.PrefixBackupRelativeFile,
		Name:                     "PrefixBackupRelativeFile",
		FullName:                 "prefix-backup-relative-file",
		CurlyFullName:            "{prefix-backup-relative-file}",
		CompiledTemplateFullPath: `{prefix}\{backup}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{backup}",
			"{relative}",
			"{file}",
		},
	},
	pathpatterntype.PrefixBackupRandomRelativeFile: {
		PathType:                 pathpatterntype.PrefixBackupRandomRelativeFile,
		Name:                     "PrefixBackupRandomRelativeFile",
		FullName:                 "prefix-backup-random-relative-file",
		CurlyFullName:            "{prefix-backup-random-relative-file}",
		CompiledTemplateFullPath: `{prefix}\{backup}\{random}\{relative}\{file}`,
		AssociatedTemplatePaths: []string{
			"{prefix}",
			"{backup}",
			"{random}",
			"{relative}",
			"{file}",
		},
	},
}
