package ftpcmdnames

import (
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	Ranges = [...]string{
		Invalid:                "Invalid",
		Help:                   "Help",
		Log:                    "Log",
		Status:                 "Status",
		Port:                   "Port",
		Install:                "Install",
		Uninstall:              "Uninstall",
		Disable:                "Disable",
		InstallFix:             "InstallFix",
		ServiceStart:           "ServiceStart",
		ServiceRestart:         "ServiceRestart",
		ServiceStop:            "ServiceStop",
		ServiceEnable:          "ServiceEnable",
		ChangePort:             "ChangePort",
		Enable:                 "Enable",
		WhitelistIps:           "WhitelistIps",
		BlacklistIps:           "BlacklistIps",
		AddUser:                "AddUser",
		UpdateUser:             "UpdateUser",
		RemoveUser:             "RemoveUser",
		BanUser:                "BanUser",
		BlockUser:              "BlockUser",
		ChangeUserHomeDir:      "ChangeUserHomeDir",
		ChangeUsersHomeDir:     "ChangeUsersHomeDir",
		PerUserLimit:           "PerUserLimit",
		AssignHostingPackage:   "AssignHostingPackage",
		EditConfig:             "EditConfig",
		UpdateConfig:           "UpdateConfig",
		ConfigKeyValUpdate:     "ConfigKeyValUpdate",
		EnablePam:              "EnablePam",
		EnableUnixAuth:         "EnableUnixAuth",
		DisablePam:             "DisablePam",
		DisableUnixAuth:        "DisableUnixAuth",
		SetPassivePorts:        "SetPassivePorts",
		SetSslFile:             "SetSslFile",
		JsonConfigSet:          "JsonConfigSet",
		ApplyDefaultConfig:     "ApplyDefaultConfig",
		RemoveConfigFiles:      "RemoveConfigFiles",
		ApplyDefaultPermission: "ApplyDefaultPermission",
		FixUserDirPermissions:  "FixUserDirPermissions",
		RemoveCoreConfigByKeys: "RemoveCoreConfigByKeys",
		ConfigPerFile:          "ConfigPerFile",
		AddOrUpdateConfig:      "AddOrUpdateConfig",
		AddSsl:                 "AddSsl",
		RenewSsl:               "RenewSsl",
		DryRunSsl:              "DryRunSsl",
		AutoSsl:                "AutoSsl",
		AutoRenewSsl:           "AutoRenewSsl",
		RemoveSslAll:           "RemoveSslAll",
		AddFtpDomain:           "AddFtpDomain",
		RemoveFtpDomain:        "RemoveFtpDomain",
		SetMaxLoad:             "SetMaxLoad",
		Clear:                  "Clear",
		Verify:                 "Verify",
		VerifyExistingUsers:    "VerifyExistingUsers",
		VerifyPortWorking:      "VerifyPortWorking",
		VerifySsl:              "VerifySsl",
		RemoveAll:              "RemoveAll",
		LastStates:             "LastStates",
		Sync:                   "Sync",
		SyncNow:                "SyncNow",
		SyncForce:              "SyncForce",
		CurrentStateName:       "CurrentStateName",
		Histories:              "Histories",
		ExportConfigSpecific:   "ExportConfigSpecific",
		ExportConfigAll:        "ExportConfigAll",
		ImportConfigSpecific:   "ImportConfigSpecific",
		ImportConfigAll:        "ImportConfigAll",
		ListConfig:             "ListConfig",
		WhichPort:              "WhichPort",
		List:                   "List",
		ListJson:               "ListJson",
		SearchUser:             "SearchUser",
		SearchUserByDomainName: "SearchUserByDomainName",
		SearchUserByDomain:     "SearchUserByDomain",
		Backup:                 "Backup",
		Import:                 "Import",
	}

	aliasMap = map[string]byte{
		"default-config":       ApplyDefaultConfig.Value(),
		"apply-default-config": ApplyDefaultConfig.Value(),
		"change-port":          ChangePort.Value(),
		"config-per-file":      ConfigPerFile.Value(),
		"add-update-config":    AddOrUpdateConfig.Value(),
		"per-user-limit":       PerUserLimit.Value(),
		"passive-port-range":   PassivePortRange.Value(),
		"enable-pam-auth":      EnablePam.Value(),
		"disable-pam-auth":     DisablePam.Value(),
		"enable-unix-auth":     EnableUnixAuth.Value(),
		"disable-unix-auth":    DisableUnixAuth.Value(),
		"remove-config-keys":   RemoveCoreConfigByKeys.Value(),
		"remove-config-files":  RemoveConfigFiles.Value(),
		"create-user":          AddUser.Value(),
		"update-user":          UpdateUser.Value(),
		"remove-users":         RemoveUser.Value(),
		"ban-user":             BanUser.Value(),
		"set-config":           UpdateConfig.Value(),
		"update-config":        UpdateConfig.Value(),
	}

	BasicEnumImpl = enumimpl.New.BasicByte.DefaultWithAliasMapAllCases(
		Invalid,
		Ranges[:],
		aliasMap)
)
