package iptype

import (
	"encoding/json"
	"testing"
)

func Test_IpType_Coverage(t *testing.T) {
	all := []Variant{Invalid, V4, V6}
	for _, v := range all {
		_ = v.ValueByte()
		_ = v.ValueInt()
		_ = v.ValueInt8()
		_ = v.ValueInt16()
		_ = v.ValueInt32()
		_ = v.ValueUInt16()
		_ = v.Value()
		_ = v.ValueString()
		_ = v.Name()
		_ = v.NameValue()
		_ = v.String()
		_ = v.ToNumberString()
		_ = v.RangeNamesCsv()
		_ = v.TypeName()
		_ = v.AllNameValues()
		_ = v.RangesByte()
		_ = v.RangesDynamicMap()
		_ = v.IntegerEnumRanges()
		_ = v.MinByte()
		_ = v.MaxByte()
		_ = v.MinInt()
		_ = v.MaxInt()
		_ = v.MinValueString()
		_ = v.MaxValueString()
		_, _ = v.MinMaxAny()
		_ = v.Format("name")
		_ = v.EnumType()
		_ = v.IsByteValueEqual(v.ValueByte())
		_ = v.IsValueEqual(v.ValueByte())
		_ = v.IsNameEqual(v.Name())
		_ = v.IsAnyValuesEqual(v.ValueByte())
		_ = v.IsAnyOf(v)
		_ = v.IsAnyNamesOf(v.Name())
		_ = v.IsInvalid()
		_ = v.IsValid()
		_ = v.IsV4()
		_ = v.IsV6()
		_ = v.IsVersion4()
		_ = v.IsVersion6()
		_ = v.IsIp4()
		_ = v.IsIp6()
		_ = v.IsEqual(v)
		_ = v.IsAboveOrEqual(Invalid)
		_ = v.IsLowerOrEqual(V6)
		_ = v.OnlySupportedErr("V4")
		_ = v.OnlySupportedMsgErr("m", "V4")
		_ = v.ToPtr()
		_ = v.Json()
		_ = v.JsonPtr()
		_ = v.AsJsoner()
		_ = v.AsJsonContractsBinder()
		_ = v.AsJsonMarshaller()
		_ = v.AsBasicByteEnumContractsBinder()
		_ = v.AsBasicEnumContractsBinder()

		raw, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		var rt Variant
		_ = json.Unmarshal(raw, &rt)
	}

	_ = GetUsingIpString("")
	_ = GetUsingIpString("192.168.1.1")
	_ = GetUsingIpString("fe80::1")
	_ = CreateTypeUsingExplicit("ipv4")
	_ = CreateTypeUsingExplicit("IpV4")
	_ = CreateTypeUsingExplicit("ipv6")
	_ = IsV4("IpV4")
	_ = IsV6("IpV6")
	_ = Is("IpV4", V4)
	_ = Is("garbage", V4)
	_, _ = New("IpV4")
	_, _ = New("garbage")
	_ = NewMust("IpV4")
	_ = ValidationError("x", V4)
	_ = V4ValidationError("x")
	_ = V6ValidationError("x")
}
