package linuxtype

import (
	"github.com/alimtvnetwork/core-v8/coredata/coredynamic"
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	Ranges = [...]string{
		Invalid:              "Invalid",
		UbuntuServer:         "UbuntuServer",
		UbuntuServer18:       "UbuntuServer18",
		UbuntuServer19:       "UbuntuServer19",
		UbuntuServer20:       "UbuntuServer20",
		UbuntuServer21:       "UbuntuServer21",
		UbuntuServer22:       "UbuntuServer22",
		UbuntuServer23:       "UbuntuServer23",
		Centos:               "Centos",
		Centos7:              "Centos7",
		Centos8:              "Centos8",
		Centos9:              "Centos9",
		Centos10:             "Centos10",
		Centos11:             "Centos11",
		Centos12:             "Centos12",
		CentosStream:         "CentosStream",
		DebianServer:         "DebianServer",
		DebianServer7:        "DebianServer7",
		DebianServer8:        "DebianServer8",
		DebianServer9:        "DebianServer9",
		DebianServer10:       "DebianServer10",
		DebianServer11:       "DebianServer11",
		DebianServer12:       "DebianServer12",
		DebianServer13:       "DebianServer13",
		DebianServer14:       "DebianServer14",
		DebianDesktop:        "DebianDesktop",
		Docker:               "Docker",
		DockerUbuntuServer:   "DockerUbuntuServer",
		DockerUbuntuServer18: "DockerUbuntuServer18",
		DockerUbuntuServer19: "DockerUbuntuServer19",
		DockerUbuntuServer20: "DockerUbuntuServer20",
		DockerUbuntuServer21: "DockerUbuntuServer21",
		DockerUbuntuServer22: "DockerUbuntuServer22",
		DockerCentos7:        "DockerCentos7",
		DockerCentos8:        "DockerCentos8",
		DockerCentos9:        "DockerCentos9",
		DockerCentos10:       "DockerCentos10",
		Android:              "Android",
		UbuntuDesktop:        "UbuntuDesktop",
	}

	osNamesMap = [...]string{
		Invalid:              "Invalid",
		UbuntuServer:         "UbuntuServer",
		UbuntuServer18:       "UbuntuServer",
		UbuntuServer19:       "UbuntuServer",
		UbuntuServer20:       "UbuntuServer",
		UbuntuServer21:       "UbuntuServer",
		UbuntuServer22:       "UbuntuServer",
		UbuntuServer23:       "UbuntuServer",
		Centos:               "Centos",
		Centos7:              "Centos",
		Centos8:              "Centos",
		Centos9:              "Centos",
		Centos10:             "Centos",
		Centos11:             "Centos",
		Centos12:             "Centos",
		CentosStream:         "CentosStream",
		DebianServer:         "DebianServer",
		DebianServer7:        "DebianServer",
		DebianServer8:        "DebianServer",
		DebianServer9:        "DebianServer",
		DebianServer10:       "DebianServer",
		DebianServer11:       "DebianServer",
		DebianServer12:       "DebianServer",
		DebianServer13:       "DebianServer",
		DebianServer14:       "DebianServer",
		DebianDesktop:        "DebianDesktop",
		Docker:               "Docker",
		DockerUbuntuServer:   "DockerUbuntuServer",
		DockerUbuntuServer18: "DockerUbuntuServer",
		DockerUbuntuServer19: "DockerUbuntuServer",
		DockerUbuntuServer20: "DockerUbuntuServer",
		DockerUbuntuServer21: "DockerUbuntuServer",
		DockerUbuntuServer22: "DockerUbuntuServer",
		DockerCentos7:        "DockerCentos",
		DockerCentos8:        "DockerCentos",
		DockerCentos9:        "DockerCentos",
		DockerCentos10:       "DockerCentos",
		Android:              "Android",
		UbuntuDesktop:        "UbuntuDesktop",
	}

	versionMap = map[Variant]string{
		Invalid:              "",
		UbuntuServer:         "UbuntuServer",
		UbuntuServer18:       "18",
		UbuntuServer19:       "19",
		UbuntuServer20:       "20",
		UbuntuServer21:       "21",
		UbuntuServer22:       "22",
		UbuntuServer23:       "23",
		Centos:               "Centos",
		Centos7:              "7",
		Centos8:              "8",
		Centos9:              "9",
		Centos10:             "10",
		Centos11:             "11",
		Centos12:             "12",
		CentosStream:         "CentosStream",
		DebianServer:         "11",
		DebianServer7:        "7",
		DebianServer8:        "8",
		DebianServer9:        "9",
		DebianServer10:       "10",
		DebianServer11:       "11",
		DebianServer12:       "12",
		DebianServer13:       "13",
		DebianServer14:       "14",
		DebianDesktop:        "DebianDesktop",
		Docker:               "Docker",
		DockerUbuntuServer:   "DockerUbuntuServer",
		DockerUbuntuServer18: "18",
		DockerUbuntuServer19: "19",
		DockerUbuntuServer20: "20",
		DockerUbuntuServer21: "21",
		DockerUbuntuServer22: "22",
		DockerCentos7:        "7",
		DockerCentos8:        "8",
		DockerCentos9:        "9",
		DockerCentos10:       "10",
		Android:              "Android",
		UbuntuDesktop:        "UbuntuDesktop",
	}

	isUbuntuServerMap = map[Variant]bool{
		UbuntuServer:   true,
		UbuntuServer18: true,
		UbuntuServer19: true,
		UbuntuServer20: true,
		UbuntuServer21: true,
		UbuntuServer22: true,
		UbuntuServer23: true,
	}

	isUbuntuDesktopMap = map[Variant]bool{
		UbuntuDesktop: true,
	}

	BasicEnumImpl = enumimpl.New.BasicByte.UsingTypeSlice(
		coredynamic.TypeName(Invalid),
		Ranges[:])
)
