package dnscmdnames

import (
	"github.com/alimtvnetwork/core-v8/coredata/coredynamic"
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	Ranges = [...]string{
		Invalid:                        "Invalid",
		Help:                           "Help",
		Log:                            "Log",
		Status:                         "Status",
		Port:                           "Port",
		Install:                        "Install",
		Uninstall:                      "Uninstall",
		Disable:                        "Disable",
		InstallFix:                     "InstallFix",
		ServiceStart:                   "ServiceStart",
		ServiceRestart:                 "ServiceRestart",
		ServiceStop:                    "ServiceStop",
		ServiceEnable:                  "ServiceEnable",
		AddDomainDefaults:              "AddDomainDefaults",
		AddMailDefaults:                "AddMailDefaults",
		AddDomain:                      "AddDomain",
		AddZone:                        "AddZone",
		AddRecord:                      "AddRecord",
		AddRecordPrompt:                "AddRecordPrompt",
		AddRecordJson:                  "AddRecordJson",
		AddOrUpdateRecord:              "AddOrUpdateRecord",
		AddOrUpdateRecordPrompt:        "AddOrUpdateRecordPrompt",
		AddOrUpdateRecordJson:          "AddOrUpdateRecordJson",
		AddARecord:                     "AddARecord", // https://t.ly/sjAC
		AddCnameRecord:                 "AddCnameRecord",
		AddMxRecord:                    "AddMxRecord",
		AddDmarcRecord:                 "AddDmarcRecord",
		AddDomainKeyRecord:             "AddDomainKeyRecord",
		AddSmtpRecord:                  "AddSmtpRecord",
		AddTxtRecord:                   "AddTxtRecord",
		AddImapRecord:                  "AddImapRecord",
		AddWwwRecord:                   "AddWwwRecord",
		AddMailRecord:                  "AddMailRecord",
		AddAcmeChallengeRecord:         "AddAcmeChallengeRecord",
		AddSoaRecord:                   "AddSoaRecord",
		AddSoaRecordPrompt:             "AddSoaRecordPrompt",
		AddSoaRecordJson:               "AddSoaRecordJson",
		AddSameIpForHostname:           "AddSameIpForHostname", // https://t.ly/TXXJ
		UpdateRecord:                   "UpdateRecord",
		UpdateCnameRecord:              "UpdateCnameRecord",
		UpdateMxRecord:                 "UpdateMxRecord",
		UpdateDmarcRecord:              "UpdateDmarcRecord",
		UpdateDomainKeyRecord:          "UpdateDomainKeyRecord",
		UpdateSmtpRecord:               "UpdateSmtpRecord",
		UpdateTxtRecord:                "UpdateTxtRecord",
		UpdateImapRecord:               "UpdateImapRecord",
		UpdateWwwRecord:                "UpdateWwwRecord",
		UpdateMailRecord:               "UpdateMailRecord",
		UpdateAcmeChallengeRecord:      "UpdateAcmeChallengeRecord",
		UpdateSoaRecord:                "UpdateSoaRecord",
		AddOrUpdateCnameRecord:         "AddOrUpdateCnameRecord",
		AddOrUpdateMxRecord:            "AddOrUpdateMxRecord",
		AddOrUpdateDmarcRecord:         "AddOrUpdateDmarcRecord",
		AddOrUpdateDomainKeyRecord:     "AddOrUpdateDomainKeyRecord",
		AddOrUpdateSmtpRecord:          "AddOrUpdateSmtpRecord",
		AddOrUpdateTxtRecord:           "AddOrUpdateTxtRecord",
		AddOrUpdateImapRecord:          "AddOrUpdateImapRecord",
		AddOrUpdateWwwRecord:           "AddOrUpdateWwwRecord",
		AddOrUpdateMailRecord:          "AddOrUpdateMailRecord",
		AddOrUpdateAcmeChallengeRecord: "AddOrUpdateAcmeChallengeRecord",
		AddOrUpdateSoaRecord:           "AddOrUpdateSoaRecord",
		HasRecord:                      "HasRecord",
		RemoveRecord:                   "RemoveRecord",
		RemoveAcmeChallenge:            "RemoveAcmeChallenge",
		RemoveRecordOnExist:            "RemoveRecordOnExist",
		RemoveDomain:                   "RemoveDomain",
		RemoveZone:                     "RemoveZone",
		RemoveNameserver:               "RemoveNameserver",
		ChangeMailServer:               "ChangeMailServer",
		Revert:                         "Revert",
		ChangePort:                     "ChangePort",
		PortStatus:                     "PortStatus",
		Lookup:                         "Lookup",
		Dig:                            "Dig",
		WhichPort:                      "WhichPort",
		ClearAll:                       "ClearAll",
		IsRunningOkay:                  "IsRunningOkay",
		DbLocation:                     "DbLocation",
		ApplyDefaultConfig:             "ApplyDefaultConfig",
		EnableFirewallPort:             "EnableFirewallPort",
		DisableFirewallPort:            "DisableFirewallPort",
		StateChange:                    "StateChange",
		MacroHistories:                 "MacroHistories",
		RemoveMacro:                    "RemoveMacro",
		ExportMacro:                    "ExportMacro",
		ImportMacro:                    "ImportMacro",
		SearchDomains:                  "SearchDomains",
		SearchTypedRecords:             "SearchTypedRecords",
		SearchZone:                     "SearchZone",
		SearchNameServers:              "SearchNameServers",
		ListNameservers:                "ListNameservers",
		ListTypedRecords:               "ListTypedRecords",
		ListZones:                      "ListZones",
		ListCNames:                     "ListCNames",
		ListDomains:                    "ListDomains",
		ListJson:                       "ListJson",
		List:                           "List",
		Histories:                      "Histories",
		Backup:                         "Backup",
		Import:                         "Import",
	}

	BasicEnumImpl = enumimpl.New.BasicByte.UsingTypeSlice(
		coredynamic.TypeName(Invalid),
		Ranges[:])
)
