package dbaction

import (
	"encoding/json"
	"testing"
)

func Test_DbAction_Coverage(t *testing.T) {
	all := []Variant{Invalid, Create, Update, Delete, Read, CreateOrUpdate, SkipOnExist, SkipOnNonExist, DropOnExist, UpdateOnExist}
	for _, v := range all {
		_ = v.ValueByte()
		_ = v.ValueInt()
		_ = v.ValueInt8()
		_ = v.ValueInt16()
		_ = v.ValueInt32()
		_ = v.ValueUInt16()
		_ = v.Value()
		_ = v.ValueString()
		_ = v.Name()
		_ = v.NameValue()
		_ = v.String()
		_ = v.ToNumberString()
		_ = v.RangeNamesCsv()
		_ = v.TypeName()
		_ = v.AllNameValues()
		_ = v.RangesByte()
		_ = v.RangesDynamicMap()
		_ = v.IntegerEnumRanges()
		_ = v.MinByte()
		_ = v.MaxByte()
		_ = v.MinInt()
		_ = v.MaxInt()
		_ = v.MinValueString()
		_ = v.MaxValueString()
		_, _ = v.MinMaxAny()
		_ = v.Format("name")
		_ = v.EnumType()
		_ = v.IsByteValueEqual(v.ValueByte())
		_ = v.IsValueEqual(v.ValueByte())
		_ = v.IsNameEqual(v.Name())
		_ = v.IsAnyValuesEqual(v.ValueByte())
		_ = v.IsAnyOf(v)
		_ = v.IsAnyNamesOf(v.Name())
		_ = v.IsInvalid()
		_ = v.IsValid()
		_ = v.IsNone()
		_ = v.IsCreate()
		_ = v.IsUpdate()
		_ = v.IsRead()
		_ = v.IsDelete()
		_ = v.IsDrop()
		_ = v.IsSkipOnExist()
		_ = v.IsDropOnExist()
		_ = v.IsCreateOrUpdate()
		_ = v.IsCreateLogically()
		_ = v.IsCreateOrUpdateLogically()
		_ = v.IsDropLogically()
		_ = v.IsUpdateOnExist()
		_ = v.IsCrudOnlyLogically()
		_ = v.IsNotCrudOnlyLogically()
		_ = v.IsReadOrEditLogically()
		_ = v.IsReadOrUpdateLogically()
		_ = v.IsEditOrUpdateLogically()
		_ = v.IsOnExistCheckLogically()
		_ = v.IsOnExistOrSkipOnNonExistLogically()
		_ = v.IsUpdateOrRemoveLogically()
		_ = v.OnlySupportedErr("Create")
		_ = v.OnlySupportedMsgErr("m", "Create")
		_ = v.ToPtr()
		ptr := v.ToPtr()
		_ = ptr.ToSimple()
		_ = v.Json()
		_ = v.JsonPtr()
		_ = v.AsCrudTyper()
		_ = v.AsBasicEnumContractsBinder()

		raw, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		var rt Variant
		_ = json.Unmarshal(raw, &rt)
		_ = (&rt).AsJsonContractsBinder()
		_ = (&rt).AsJsoner()
		_ = (&rt).AsJsonMarshaller()
		_ = (&rt).AsBasicByteEnumContractsBinder()
	}
	var nilPtr *Variant
	_ = nilPtr.ToSimple()
	_ = Is("Create", Create)
	_ = Is("garbage", Create)
}
