package pathpatterntype

import (
	"github.com/alimtvnetwork/core-v8/coredata/coredynamic"
	"github.com/alimtvnetwork/core-v8/coreimpl/enumimpl"
)

var (
	rangesMap = [...]string{
		Invalid:                            "Invalid",
		Root:                               "Root",
		VariableDir:                        "VariableDir",
		App:                                "App",
		AppCore:                            "AppCore",
		Id:                                 "Id",
		File:                               "File",
		VarApp:                             "VarApp",
		AppConfigStore:                     "AppConfigStore",
		AppLog:                             "AppLog",
		AppDb:                              "AppDb",
		AppTest:                            "AppTest",
		AppTemp:                            "AppTemp",
		VarAppTemp:                         "VarAppTemp",
		Relative:                           "Relative",
		RelativeId:                         "RelativeId",
		RelativeIdFile:                     "RelativeIdFile",
		AppRelative:                        "AppRelative",
		AppRelativeId:                      "AppRelativeId",
		AppRelativeIdFile:                  "AppRelativeIdFile",
		PrefixApp:                          "PrefixApp",
		PrefixAppRelative:                  "PrefixAppRelative",
		PrefixAppRelativeId:                "PrefixAppRelativeId",
		PrefixAppRelativeIdFile:            "PrefixAppRelativeIdFile",
		TempRoot:                           "TempRoot",
		AppInstalled:                       "AppInstalled",
		AppDownloads:                       "AppDownloads",
		Home:                               "Home",
		User:                               "User",
		HomeUser:                           "HomeUser",
		HomeUserApp:                        "HomeUserApp",
		UsersRoot:                          "UsersRoot",
		WebServerRoot:                      "WebServerRoot",
		WebServerConfigsRoot:               "WebServerConfigsRoot",
		WebServerConfigsUsersRoot:          "WebServerConfigsUsersRoot",
		Packages:                           "Packages",
		Instructions:                       "Instructions",
		VarAppPackages:                     "VarAppPackages",
		VarAppDownloads:                    "VarAppDownloads",
		VarAppInstructions:                 "VarAppInstructions",
		VarAppLog:                          "VarAppLog",
		VarAppLogId:                        "VarAppLogId",
		IdFile:                             "IdFile",
		LogFile:                            "LogFile",
		LogId:                              "LogId",
		DbId:                               "DbId",
		DbIdFile:                           "DbIdFile",
		ConfigStore:                        "ConfigStore",
		Log:                                "Log",
		Database:                           "Database",
		Test:                               "Test",
		Temp:                               "Temp",
		Prefix:                             "Prefix",
		Downloads:                          "Downloads",
		Extension:                          "Extension",
		FileWithExtension:                  "FileWithExtension",
		Webserver:                          "Webserver",
		PrefixAppFile:                      "PrefixAppFile",
		AppFileWithExtension:               "AppFileWithExtension",
		PrefixAppFileWithExtension:         "PrefixAppFileWithExtension",
		PrefixRelativeAppFileWithExtension: "PrefixRelativeAppFileWithExtension",
		UserTemp:                           "UserTemp",
		Audit:                              "Audit",
		LogDb:                              "LogDb",
		LogDbFile:                          "LogDbFile",
		LogAppDb:                           "LogAppDb",
		LogAppDbFile:                       "LogAppDbFile",
		TempUser:                           "TempUser",
		TempApp:                            "TempApp",
		TempAudit:                          "TempAudit",
		LogApp:                             "LogApp",
		LogAppFile:                         "LogAppFile",
		Random:                             "Random",
		RandomUuid:                         "RandomUuid",
		RandomNumber:                       "RandomNumber",
		AppDbFile:                          "AppDbFile",
		AppDbRelativeFile:                  "AppDbRelativeFile",
		AppDbRandom:                        "AppDbRandom",
		AppDbRandomRelative:                "AppDbRandomRelative",
		AppDbRandomRelativeFile:            "AppDbRandomRelativeFile",
		LogRandom:                          "LogRandom",
		AppDbRandomFile:                    "AppDbRandomFile",
		LogRandomFile:                      "LogRandomFile",
		VarAppRandom:                       "VarAppRandom",
		VarAppRandomFile:                   "VarAppRandomFile",
		VarAppRandomRelative:               "VarAppRandomRelative",
		VarAppRandomRelativeFile:           "VarAppRandomRelativeFile",
		Specific:                           "Specific",
		Backup:                             "Backup",
		HomeBackup:                         "HomeBackup",
		BackupSpecific:                     "BackupSpecific",
		BackupRelative:                     "BackupRelative",
		Ssl:                                "Ssl",
		WebServerSsl:                       "WebServerSsl",
		WebServerConfigUsers:               "WebServerConfigUsers",
		WebServerConfigUsersSpecific:       "WebServerConfigUsersSpecific",
		WebServerConfigSsl:                 "WebServerConfigSsl",
		RelativeSsl:                        "RelativeSsl",
		VarAppBackup:                       "VarAppBackup",
		VarAppBackupFile:                   "VarAppBackupFile",
		VarAppBackupRandom:                 "VarAppBackupRandom",
		VarAppBackupRandomFile:             "VarAppBackupRandomFile",
		VarAppBackupRandomRelative:         "VarAppBackupRandomRelative",
		VarAppBackupRandomRelativeFile:     "VarAppBackupRandomRelativeFile",
		Config:                             "Config",
		Users:                              "Users",
		BackupFile:                         "BackupFile",
		BackupRelativeFile:                 "BackupRelativeFile",
		PrefixBackup:                       "PrefixBackup",
		PrefixBackupFile:                   "PrefixBackupFile",
		PrefixBackupRelativeFile:           "PrefixBackupRelativeFile",
		PrefixBackupRandomRelativeFile:     "PrefixBackupRandomRelativeFile",
	}

	curlyCompilerFunc = func(patternType Variant) string {
		return patternType.CurlyPathFullName()
	}

	nonCurlyCompilerFunc = func(patternType Variant) string {
		return patternType.PathFullName()
	}

	BasicEnumImpl = enumimpl.New.BasicByte.UsingTypeSlice(
		coredynamic.TypeName(Invalid),
		rangesMap[:])
)
